const WORD_CATALOG = [
  {id:"word_abandon",word:"abandon",meaning:"放棄する",hint:"abandon a plan",partOfSpeech:"verb",learningProfile:{scoreTier:600,difficulty:3,priority:4},tags:["business","planning"]},
  {id:"word_acquire",word:"acquire",meaning:"獲得する",hint:"会社や技能を手に入れる",partOfSpeech:"verb",learningProfile:{scoreTier:600,difficulty:3,priority:4},tags:["business","skills"]},
  {id:"word_additional",word:"additional",meaning:"追加の",hint:"addの仲間",partOfSpeech:"adjective",learningProfile:{scoreTier:500,difficulty:2,priority:4},tags:["business","general"]},
  {id:"word_adequate",word:"adequate",meaning:"十分な",hint:"必要量を満たす",partOfSpeech:"adjective",learningProfile:{scoreTier:600,difficulty:3,priority:3},tags:["business","evaluation"]},
  {id:"word_approximately",word:"approximately",meaning:"およそ",hint:"aboutと同じ感覚",partOfSpeech:"adverb",learningProfile:{scoreTier:600,difficulty:3,priority:4},tags:["numbers","reports"]},
  {id:"word_arrange",word:"arrange",meaning:"手配する、整える",hint:"予定や物を整える",partOfSpeech:"verb",learningProfile:{scoreTier:500,difficulty:2,priority:5},tags:["scheduling","business"]},
  {id:"word_available",word:"available",meaning:"利用できる、空いている",hint:"人・物・時間に使う",partOfSpeech:"adjective",learningProfile:{scoreTier:400,difficulty:2,priority:5},tags:["scheduling","general"]},
  {id:"word_benefit",word:"benefit",meaning:"利益、恩恵",hint:"beneficialもセット",partOfSpeech:"noun, verb",learningProfile:{scoreTier:400,difficulty:2,priority:5},tags:["business","employment"]},
  {id:"word_confirm",word:"confirm",meaning:"確認する",hint:"予約確認で頻出",partOfSpeech:"verb",learningProfile:{scoreTier:400,difficulty:2,priority:5},tags:["reservations","communication"]},
  {id:"word_conduct",word:"conduct",meaning:"実施する",hint:"conduct a survey",partOfSpeech:"verb",learningProfile:{scoreTier:600,difficulty:3,priority:4},tags:["research","business"]},
  {id:"word_consider",word:"consider",meaning:"検討する",hint:"consider doing",partOfSpeech:"verb",learningProfile:{scoreTier:400,difficulty:2,priority:5},tags:["planning","decision"]},
  {id:"word_contract",word:"contract",meaning:"契約",hint:"sign a contract",partOfSpeech:"noun",learningProfile:{scoreTier:400,difficulty:2,priority:5},tags:["contracts","business"]},
  {id:"word_convenient",word:"convenient",meaning:"便利な",hint:"場所や時間にも使う",partOfSpeech:"adjective",learningProfile:{scoreTier:500,difficulty:2,priority:4},tags:["services","general"]},
  {id:"word_delay",word:"delay",meaning:"遅らせる、遅延",hint:"flight delay",partOfSpeech:"noun, verb",learningProfile:{scoreTier:400,difficulty:2,priority:5},tags:["travel","scheduling"]},
  {id:"word_deliver",word:"deliver",meaning:"配達する、届ける",hint:"deliveryの動詞",partOfSpeech:"verb",learningProfile:{scoreTier:400,difficulty:2,priority:5},tags:["shipping","business"]},
  {id:"word_department",word:"department",meaning:"部門、部署",hint:"sales department",partOfSpeech:"noun",learningProfile:{scoreTier:400,difficulty:2,priority:5},tags:["company","organization"]},
  {id:"word_despite",word:"despite",meaning:"〜にもかかわらず",hint:"後ろは名詞",partOfSpeech:"preposition",learningProfile:{scoreTier:600,difficulty:3,priority:4},tags:["grammar","general"]},
  {id:"word_determine",word:"determine",meaning:"決定する",hint:"determine whether",partOfSpeech:"verb",learningProfile:{scoreTier:600,difficulty:3,priority:4},tags:["decision","business"]},
  {id:"word_effective",word:"effective",meaning:"効果的な",hint:"effectは名詞",partOfSpeech:"adjective",learningProfile:{scoreTier:500,difficulty:2,priority:5},tags:["evaluation","business"]},
  {id:"word_employee",word:"employee",meaning:"従業員",hint:"employerは雇用主",partOfSpeech:"noun",learningProfile:{scoreTier:400,difficulty:2,priority:5},tags:["employment","company"]},
  {id:"word_ensure",word:"ensure",meaning:"確実にする",hint:"make sureに近い",partOfSpeech:"verb",learningProfile:{scoreTier:500,difficulty:3,priority:5},tags:["quality","business"]},
  {id:"word_equipment",word:"equipment",meaning:"設備、機器",hint:"不可算名詞",partOfSpeech:"noun",learningProfile:{scoreTier:500,difficulty:2,priority:5},tags:["office","facilities"]},
  {id:"word_estimate",word:"estimate",meaning:"見積もる、見積もり",hint:"price estimate",partOfSpeech:"noun, verb",learningProfile:{scoreTier:500,difficulty:3,priority:5},tags:["finance","planning"]},
  {id:"word_facility",word:"facility",meaning:"施設、設備",hint:"複数形facilitiesも頻出",partOfSpeech:"noun",learningProfile:{scoreTier:500,difficulty:3,priority:5},tags:["facilities","company"]},
  {id:"word_frequently",word:"frequently",meaning:"頻繁に",hint:"oftenより硬め",partOfSpeech:"adverb",learningProfile:{scoreTier:500,difficulty:2,priority:4},tags:["frequency","general"]},
  {id:"word_increase",word:"increase",meaning:"増加する、増加",hint:"名詞と動詞",partOfSpeech:"noun, verb",learningProfile:{scoreTier:400,difficulty:2,priority:5},tags:["reports","finance"]},
  {id:"word_indicate",word:"indicate",meaning:"示す",hint:"グラフ説明で頻出",partOfSpeech:"verb",learningProfile:{scoreTier:600,difficulty:3,priority:5},tags:["reports","data"]},
  {id:"word_maintain",word:"maintain",meaning:"維持する",hint:"maintenanceもセット",partOfSpeech:"verb",learningProfile:{scoreTier:500,difficulty:3,priority:5},tags:["facilities","quality"]},
  {id:"word_negotiate",word:"negotiate",meaning:"交渉する",hint:"negotiate with",partOfSpeech:"verb",learningProfile:{scoreTier:600,difficulty:4,priority:4},tags:["contracts","communication"]},
  {id:"word_notify",word:"notify",meaning:"知らせる",hint:"notify A of B",partOfSpeech:"verb",learningProfile:{scoreTier:500,difficulty:3,priority:5},tags:["communication","business"]},
  {id:"word_participate",word:"participate",meaning:"参加する",hint:"participate in",partOfSpeech:"verb",learningProfile:{scoreTier:500,difficulty:3,priority:5},tags:["events","meetings"]},
  {id:"word_policy",word:"policy",meaning:"方針、規定",hint:"company policy",partOfSpeech:"noun",learningProfile:{scoreTier:400,difficulty:2,priority:5},tags:["company","rules"]},
  {id:"word_postpone",word:"postpone",meaning:"延期する",hint:"put offと同じ",partOfSpeech:"verb",learningProfile:{scoreTier:600,difficulty:3,priority:4},tags:["scheduling","events"]},
  {id:"word_purchase",word:"purchase",meaning:"購入する、購入",hint:"buyより硬い",partOfSpeech:"noun, verb",learningProfile:{scoreTier:400,difficulty:2,priority:5},tags:["purchasing","business"]},
  {id:"word_require",word:"require",meaning:"必要とする",hint:"require A to do",partOfSpeech:"verb",learningProfile:{scoreTier:500,difficulty:2,priority:5},tags:["rules","business"]},
  {id:"word_schedule",word:"schedule",meaning:"予定、予定を組む",hint:"発音はスケジュール",partOfSpeech:"noun, verb",learningProfile:{scoreTier:400,difficulty:2,priority:5},tags:["scheduling","business"]},
  {id:"word_submit",word:"submit",meaning:"提出する",hint:"submit a report",partOfSpeech:"verb",learningProfile:{scoreTier:500,difficulty:3,priority:5},tags:["documents","business"]},
  {id:"word_temporary",word:"temporary",meaning:"一時的な",hint:"temporary staff",partOfSpeech:"adjective",learningProfile:{scoreTier:500,difficulty:3,priority:4},tags:["employment","general"]},
  {id:"word_vacant",word:"vacant",meaning:"空いている",hint:"部屋・役職に使う",partOfSpeech:"adjective",learningProfile:{scoreTier:500,difficulty:3,priority:4},tags:["employment","property"]},
  {id:"word_verify",word:"verify",meaning:"確認する、検証する",hint:"情報が正しいか確かめる",partOfSpeech:"verb",learningProfile:{scoreTier:600,difficulty:3,priority:4},tags:["quality","data"]}
];
